apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name.external}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: {{.Values.deployment.name}}
  type: {{.Values.service.type}}
  ports:
    - protocol: TCP
      port: 80
